name: Deploy to Pinata

on:
  push:
    branches:
      - main  # Remplace avec ta branche principale si nécessaire

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Pinata
        env:
          PINATA_API_KEY: ${{ secrets.PINATA_API_KEY }}
          PINATA_API_SECRET: ${{ secrets.PINATA_API_SECRET }}
        run: |
          # Installer Pinata SDK
          npm install @pinata/sdk
          
          # Uploader les fichiers du répertoire 'Torrent' vers Pinata
          node -e "
            const fs = require('fs');
            const path = require('path');
            const pinataSDK = require('@pinata/sdk');
            const pinata = pinataSDK(process.env.PINATA_API_KEY, process.env.PINATA_API_SECRET);

            const directoryPath = path.join(__dirname, 'Torrent');  # Utilise le dossier 'Torrent'
            const files = fs.readdirSync(directoryPath);

            const filePromises = files.map(file => {
              return pinata.pinFromFS(path.join(directoryPath, file));
            });

            Promise.all(filePromises)
              .then(results => {
                console.log('Successfully uploaded to Pinata:', results);
              })
              .catch(err => {
                console.error('Error uploading to Pinata:', err);
              });
          "
