name: Deploy to IPFS

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install IPFS via script
        run: |
          # Télécharger et installer IPFS via le script d'installation officiel
          curl https://raw.githubusercontent.com/ipfs/go-ipfs/master/install.sh | sudo bash

      - name: Add files to IPFS
        run: |
          # Ajouter tous les fichiers du dépôt au réseau IPFS
          ipfs add -r . # Cela retournera un CID que tu pourras utiliser plus tard

      - name: Pin to Pinata IPFS Service
        env:
          PINATA_API_KEY: ${{ secrets.PINATA_API_KEY }}
          PINATA_API_SECRET: ${{ secrets.PINATA_API_SECRET }}
        run: |
          # Utiliser curl pour épingler l'objet IPFS sur Pinata
          CID=$(ipfs add -r . | tail -n 1 | awk '{print $2}')  # Récupère le dernier CID retourné
          curl -X POST https://api.pinata.cloud/pinning/pinByCid \
            -H "pinata_api_key: $PINATA_API_KEY" \
            -H "pinata_secret_api_key: $PINATA_API_SECRET" \
            -d "{\"cid\": \"$CID\"}"
